# 最终生成的配置文件请查看config/index.js

# 应用名
name: 'rocket-upload-server'

# 服务端口
port: 4000

# 服务前缀
apiPrefix: '/rocket-upload-server/api'

# apidoc 文档前缀
apiDocPrefix: '/rocket-upload-server/apidoc'

# 上传后的静态资源 url访问路径（注 和 groupDir 保持一致
apiGroupAssetsPrefix: '/rocket-upload-server/group'

# 上传后保存的静态资源磁盘路径
assetsPath:
  prod: '/var/log/rocket-upload-server'

# 组合文件夹的名字
groupDir: 'group'

#  支持上传的类型
uploadType: [Image,Video,Audio,Doc]

# 支持的图片类型，TODO 后续从配置中心拿取
imageExtnameValida: [jpg,jpeg,bmp,gif,png,tiff,pcx,webp]

# 支持的视频类型，TODO 后续从配置中心拿取
videoExtnameValida: [mp4,]

# 支持的音频类型，TODO 后续从配置中心拿取
audioExtnameValida: []

# 支持的文本类型，TODO 后续从配置中心拿取
documentExtnameValida: []

# 给上传的 app 加密解密的密钥
uploadAppSecretKey: RocketUploadServerAppKeydxs01w3z

# 支持上传 App & 类型 & 秘钥，TODO 后续从配置中心拿取（数据库，待移除
uploadApp:
  testApp:
    secret: 1fdb6a99c7ba1d
    uploadType: [ testAppImage ]
  aicenter:
    secret: 6c04b5180a099119
    uploadType: [aicenterImage]

