# 最终生成的配置文件请查看config/index.js

# 应用名
name: 'rocket-upload-server'

# 服务端口
port: 4000

# 服务前缀
apiPrefix: '/rocket-upload-server/api'

# apidoc 文档前缀
apiDocPrefix: '/rocket-upload-server/apidoc'

# 上传后保存的静态资源磁盘路径
assetsPath:
  prod: '/var/log/rocket-upload-server'

# 支持的图片类型，TODO 后续从配置中心拿取
imageExtnameValida: [jpg,jpeg,bmp,gif,png,tiff,pcx,webp]

# 支持的视频类型，TODO 后续从配置中心拿取
videoExtnameValida: [mp4,]

# 支持的音频类型，TODO 后续从配置中心拿取
audioExtnameValida: []

# 支持的文本类型，TODO 后续从配置中心拿取
documentExtnameValida: []
